subscriber: rename Context's field `subscriber` to `collector`
tokio-rs/tracing pull request #1257
Opened 2021-02-20 03:05 UTC by Folyd

This PR:
- Rename `Context`'s field `subscriber` to `collector`.
- Make the `Clone` implementation for `Context` more idiomatic.

2021-02-20 19:59 UTC, davidbarsky approved these changes

2021-02-23 18:33 UTC, hawkw approved these changes

2021-02-23 18:39 UTC, hawkw requested changes

2021-02-23 18:39 UTC, hawkw commented on tracing-subscriber/src/subscribe.rs
>              "the subscriber should have data for the current span ({:?})!",
we should probably also change the panic message:
```suggestion
            "the collector should have data for the current span ({:?})!",
```

2021-02-23 18:39 UTC, hawkw commented on tracing-subscriber/src/subscribe.rs
>              // return `true` so that the subscriber does not incorrectly assume that
```suggestion
            // return `true` so that the collector does not incorrectly assume that
```

2021-02-23 18:39 UTC, hawkw commented on tracing-subscriber/src/subscribe.rs
>      /// Returns the wrapped subscriber's view of the current span.
```suggestion
    /// Returns the wrapped collector's view of the current span.
```

2021-02-23 18:39 UTC, hawkw commented on tracing-subscriber/src/subscribe.rs
>      /// Returns whether the wrapped subscriber would enable the current span.
```suggestion
    /// Returns whether the wrapped collector would enable the current span.
```

2021-02-25 18:22 UTC, hawkw approved these changes
looks great, thank you!

2021-02-27 03:00 UTC, Folyd commented
One of the CI checks failed due to a Network issue. I think we need a retry?

```log
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/adler/1.0.1/download`, got 504
Warning: warning: spurious network error (1 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/adler/1.0.1/download`, got 504
error: failed to download from `https://crates.io/api/v1/crates/adler/1.0.1/download`
Error: failed to download from `https://crates.io/api/v1/crates/adler/1.0.1/download`
Caused by:
  failed to get 200 response from `https://crates.io/api/v1/crates/adler/1.0.1/download`, got 504
Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101
```

2021-05-19 08:05 UTC, Folyd commented
Ping 🍺

2021-05-23 15:42 UTC, davidbarsky commented
Thanks!

2021-05-23 15:42 UTC, merged