[WIP]: subscriber: add `MakeWriter` combinators
tokio-rs/tracing pull request #1274
Opened 2021-03-01 19:51 UTC by hawkw

depends on #1141

this is a draft since it needs docs etc, but check this out!

2021-03-01 21:33 UTC, davidbarsky requested changes
This looks _super_ cool, modulo warnings and docs! Mind re-upping me for review once that's done?

2021-06-25 18:02 UTC, hawkw commented on tracing-subscriber/src/fmt/writer.rs
> +    /// [`MakeWriter::make_writer_for`][mwf] method will check the predicate to
whoops, my bad --- i forgot to add that.

2021-06-25 18:50 UTC, hawkw commented on tracing-subscriber/src/fmt/writer.rs
> +    /// for events at or below the provided verbosity [`Level`].
hmm, the docs for `Level` mention a concept of "verbosity" but don't actually describe the comparison behavior: https://docs.rs/tracing/0.1.26/tracing/struct.Level.html we should probably add something there as well, in a separate branch. I'll merge this change for now though.

2021-06-25 20:13 UTC, hawkw commented on tracing-subscriber/src/fmt/writer.rs
> +    /// for events at or below the provided verbosity [`Level`].
opened #1446 to add a (fairly excessive) docs section explaining levels and level comparisons

2021-06-25 20:17 UTC, davidbarsky approved these changes

2021-06-25 20:30 UTC, merged