subscriber: avoid unnecessary inner `register_callsite()` call
tokio-rs/tracing pull request #1433
Opened 2021-06-10 13:51 UTC by Folyd

I'm sure we can avoid unnecessary `self.inner.register_callsite()` call in these two `Layered` implementations.

2021-06-10 17:44 UTC, hawkw requested changes
I don't think this is correct. `register_callsite` is not _just_ responsible for performing filtering, it's also responsible for notifying the collector of the existence of the callsite --- it may choose to, for example, store some data for that callsite. This change means that if the outer `Subscriber` returns `Interest::sometimes`, the inner subscriber will never have the opportunity to register a callsite that _is_ enabled. 

If the subscriber, for example, preallocates storage for spans originating at particular callsites, it may then see a span from a callsite that it never had the opportunity to prepare storage for. The intention behind calling `inner.register_callsite` before the `if` statement was to ensure that the inner subscriber is informed that the callsite exists regardless of the outer subscriber's filtering decision. So, I think this change would actually introduce a bug.

Perhaps a better solution is to add a comment on that line explaining _why_ we always call `register_callsite` on `inner`?

2021-06-11 10:52 UTC, Folyd commented
> I don't think this is correct. `register_callsite` is not _just_ responsible for performing filtering, it's also responsible for notifying the collector of the existence of the callsite --- it may choose to, for example, store some data for that callsite. This change means that if the outer `Subscriber` returns `Interest::sometimes`, the inner subscriber will never have the opportunity to register a callsite that _is_ enabled.
> 
> If the subscriber, for example, preallocates storage for spans originating at particular callsites, it may then see a span from a callsite that it never had the opportunity to prepare storage for. The intention behind calling `inner.register_callsite` before the `if` statement was to ensure that the inner subscriber is informed that the callsite exists regardless of the outer subscriber's filtering decision. So, I think this change would actually introduce a bug.
> 
> Perhaps a better solution is to add a comment on that line explaining _why_ we always call `register_callsite` on `inner`?

Thanks, @hawkw. You're right. I have updated the comments. ❤️

2021-06-23 17:55 UTC, hawkw approved these changes
lgtm, thanks!

2021-06-23 17:55 UTC, hawkw commented on tracing-subscriber/src/subscribe.rs
> +        // was to ensure that the inner subscriber is informed that the callsite exists
nit: in this context i might use present tense here:
```suggestion
        // is to ensure that the inner subscriber is informed that the callsite exists
```

2021-06-23 17:55 UTC, hawkw commented on tracing-subscriber/src/subscribe.rs
> +        // was to ensure that the inner subscriber is informed that the callsite exists
```suggestion
        // is to ensure that the inner subscriber is informed that the callsite exists
```

2021-06-23 19:14 UTC, merged