opentelemetry: prepare for 0.16.0 release
tokio-rs/tracing pull request #1877
Opened 2022-01-30 19:43 UTC by jtescher

Breaking changes in this release:

- Upgrade to `v0.17.0` of `opentelemetry` (#1853)
  For list of breaking changes in OpenTelemetry, see the [v0.17.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/CHANGELOG.md#v0170).

2022-01-30 19:45 UTC, jtescher commented
@hawkw did we want to move forward with #1869 before merging this one?

2022-02-01 21:17 UTC, davidbarsky commented
> @hawkw did we want to move forward with #1869 before merging this one?

I'm not Eliza, but yes.

2022-02-01 21:32 UTC, davidbarsky commented on tracing-opentelemetry/CHANGELOG.md
> +
```suggestion

```

2022-02-01 21:33 UTC, davidbarsky commented on tracing-opentelemetry/CHANGELOG.md
> +
```suggestion
- Disable the default `tracing-log` feature (#1869)
```

2022-02-01 21:33 UTC, davidbarsky approved these changes
If you accept my changes to the changelog, then we can merge and release this.

2022-02-01 21:34 UTC, davidbarsky commented on tracing-opentelemetry/CHANGELOG.md
> +
hrm—ignore the first suggested change. not sure why that's been added.

2022-02-01 21:41 UTC, hawkw requested changes
I just saw that #1869 just got merged, but I'm not sure if that was actually the correct solution to the problem. Let's take a minute to make sure that change was correct before we publish this release, please.

2022-02-01 22:09 UTC, jtescher commented
<details>
  <summary>Previous Discord comment context</summary>

> Hi, is it possible to separate log and tracing?
> I tried disabling tracing-log but I cannot turn-off default-features of tracing-subscriber which is a dependncy of tracing-opentelemetry

```toml
tracing-opentelemetry = { version = "0.16.0", optional = true, default-features = false }
tracing-subscriber = { version = "0.3.6", default-features = false, features = [
    "smallvec",
    "std",
] }
```

```shell
$ cargo tree -i -p tracing-log
tracing-log v0.1.2
└── tracing-subscriber v0.3.6
    ├── mylib
    └── tracing-opentelemetry v0.16.0
        └── mylib
```
</details>

I cannot reproduce that example. E.g. This example `Cargo.toml`

```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry = "0.16.0"
tracing = "0.1.29"
tracing-opentelemetry = { version = "0.16.0", default-features = false }
tracing-subscriber = { version = "0.3.6", default-features = false, features = [ "smallvec", "std", ] }
```

`tracing-log` is not included if `default-features = false`.

```shell
$ cargo tree -i -p tracing-log
error: package ID specification `tracing-log` did not match any packages
```

#1869 was not to fix the above case, but to simply not require opting out explicitly.

2022-02-03 19:17 UTC, hawkw approved these changes

2022-02-03 19:31 UTC, merged