More layer modification
tokio-rs/tracing pull request #2034
Opened 2022-03-30 00:39 UTC by wagenet

This adds more modification methods for use with reloading. Replaces #2032.

Needs fixes in doc tests.

## Motivation

I have a Filtered layer that I'd like to modify with a reload handle. If I use `reload` then the filter doesn't work. If I use `modify` with `filter_mut` I can't update the writer. 

## Solution

Adds some additional accessor methods to allow the writer to be modified in `modify`.

2022-03-30 15:10 UTC, davidbarsky requested changes
I added some grammatical fixes, but naively, I think that these examples would be better placed on `reload` with the docs here linking to those?

2022-03-30 15:10 UTC, davidbarsky commented on tracing-subscriber/src/filter/subscriber_filters/mod.rs
> +    /// # Examples
```suggestion
    /// This method is primarily expected to be used with the
    /// [`reload::Handle::modify`](crate::reload::Handle::modify) method. For example:
    ///
```

2022-03-30 15:45 UTC, wagenet commented on tracing-subscriber/src/filter/subscriber_filters/mod.rs
> +    /// Mutably borrows the underlying [`Subscribe`] that is being filtered.
@davidbarsky I just copied the wording from `filter_mut`. I agree that it could be more natural, but went for consistency.

2022-03-30 17:16 UTC, davidbarsky commented on tracing-subscriber/src/filter/subscriber_filters/mod.rs
> +    pub fn wrapped(&self) -> &S {
Yeah, I think `inner` is a better option.

2022-03-30 20:02 UTC, wagenet commented on tracing-subscriber/src/filter/subscriber_filters/mod.rs
> +    /// Borrows the underlying [`Subscribe`] that is being filtered.
Updated.

2022-03-30 20:03 UTC, wagenet commented on tracing-subscriber/src/filter/subscriber_filters/mod.rs
> +    /// # Examples
Updated.

2022-03-30 20:03 UTC, wagenet commented on tracing-subscriber/src/filter/subscriber_filters/mod.rs
> +    pub fn wrapped_mut(&mut self) -> &mut S {
Done!

2022-03-30 20:03 UTC, wagenet commented on tracing-subscriber/src/filter/subscriber_filters/mod.rs
> +    pub fn wrapped(&self) -> &S {
Done!

2022-03-30 20:03 UTC, wagenet commented on tracing-subscriber/src/filter/subscriber_filters/mod.rs
> +    /// subsrcribe. Generally, this will primarily be used with the
Fixed

2022-03-30 21:16 UTC, hawkw reviewed
one last suggestion for the documentation

2022-03-30 21:16 UTC, hawkw commented on tracing-subscriber/src/fmt/fmt_subscriber.rs
> +    /// Changes whether this should use ansi colors.
nit how about:
```suggestion
    /// Sets whether this subscriber should use ANSI terminal formatting
    /// escape codes (such as colors).
```

2022-03-30 21:45 UTC, hawkw approved these changes
looks good to me --- @davidbarsky wanna give the docs a last look?

2022-03-30 21:47 UTC, hawkw commented
@wagenet btw, you don't need to force-push changes to your branches, we'll squash the entire branch prior to merging anyway, so it's fine to make a series of messy work-in-progress commits: https://github.com/tokio-rs/tracing/blob/master/CONTRIBUTING.md#commit-squashing

2022-03-31 18:12 UTC, davidbarsky approved these changes

2022-03-31 18:19 UTC, merged