opentelemetry: Update otel to 0.18.0
tokio-rs/tracing pull request #2303
Opened 2022-09-13 03:36 UTC by jtescher

## Motivation

Support the latest OpenTelemetry specification.

## Solution

Update `opentelemetry` to the latest `0.18.x` release. Breaking changes in the metrics spec have removed value recorders and added histograms so the metrics layer's `value.` prefix has been changed to `histogram.` and behaves accordingly. Additionally the `PushController` configuration for the metrics layer has been simplified to accept a [`BasicController`](https://docs.rs/opentelemetry/0.18.0/opentelemetry/sdk/metrics/controllers/struct.BasicController.html) that can act in either push or pull modes. Finally trace sampling in the sdk's `PreSampledTracer` impl has been updated to match the sampling logic in https://github.com/open-telemetry/opentelemetry-rust/pull/839.

2022-09-15 19:11 UTC, hawkw commented
Build faiilure with `-Zminimal-versions` (https://github.com/tokio-rs/tracing/actions/runs/3055323497/jobs/4928284929) is unrelated, I'll fix that.

2022-09-15 22:22 UTC, hawkw commented
> Build faiilure with `-Zminimal-versions` (https://github.com/tokio-rs/tracing/actions/runs/3055323497/jobs/4928284929) is unrelated, I'll fix that.

Actually, I don't think this is unrelated --- the failing `async-trait` version is pulled as a dependency of `opentelemetry`. However, I'm unsure why this is happening, as we depend on a newer `async-trait` version specifically to prevent this:
https://github.com/tokio-rs/tracing/blob/84633eaa9099470f688b2c20ab5febb024a60456/tracing-opentelemetry/Cargo.toml#L35-L36
so I'm unsure what's wrong here...

2022-09-15 22:25 UTC, hawkw requested changes
It looks like the minimal versions build failure is caused by the removal of explicit dependencies on `async-trait` in `tracing-opentelemetry`'s `Cargo.toml`. 
I think if we put those back, the `-Zminimal-versions` CI build will pass again and we can move forwards with this PR.

@jtescher is there a reason the `async-trait` dependencies were removed? If we needed to get rid of them for some reason, that will complicate fixing the minimal-versions build...

2022-09-15 22:25 UTC, hawkw commented on tracing-opentelemetry/Cargo.toml
> -async-trait = "0.1.20"
We need to put this dependency back in order to fix the minimal versions build.

2022-09-15 22:25 UTC, hawkw commented on tracing-opentelemetry/Cargo.toml
> -async-trait = "0.1.56"
Similarly, we need to put this back to fix the minimal-versions build. Then CI should pass again.

2022-09-15 23:45 UTC, jtescher commented
@hawkw ah fixed, the `async-trait` usage in _this_ crate had been removed, but not the dependencies. Looks like this are passing now besides the nightly compiler bug.

2022-09-15 23:52 UTC, hawkw approved these changes
okay, great, now that the build passes, this LGTM!

I think we can safely ignore the nightly build failure, though I'm going to see if there's an existing bug report for this...

**Edit**: ah, looks like that's rust-lang/rust#101844

2022-09-15 23:54 UTC, merged

2022-09-16 15:18 UTC, purkhusid commented
Is it possible to push a new release of tracing-opentelemetry? I think this PR should fix #2306