Allow `value_set`s  of any lenght
tokio-rs/tracing pull request #2508
Opened 2023-03-14 17:06 UTC by eopb

## Motivation

closes: #1566

## Solution

This change removes the maximum of 32 fields limitation using const generics.

2023-08-24 00:09 UTC, hawkw approved these changes
I'm fine with making this change. If memory serves, I believe the motivation for the array length limit was due to Rust compiler limitations that no longer exist.

2023-09-05 17:12 UTC, hawkw requested changes
oh, before we merge this: there's a docs example stating that a span may only have 32 fields or fewer, which shows creating a span with > 32 fields and asserts that it doesn't compile: 

https://github.com/tokio-rs/tracing/blob/bf05c61b7234eb1a196ef8d30f773d3ea6b60ce9/tracing/src/lib.rs#L389-L403

Let's make sure to remove that example before merging this PR?

---

As a side note, I would _expect_ the inclusion of that example with `compile_fail` to be breaking the CI build now that it compiles...which makes me concerned that we're not actually running doctests on CI, or something...

2023-09-05 17:16 UTC, hawkw commented
Hmm, actually, it looks like that test _did_ run on this PR, and it _did_ fail to compile: https://github.com/tokio-rs/tracing/actions/runs/6087610980/job/16516577365?pr=2508#step:6:186

This makes me concerned that there's some other reason that test doesn't compile, in addition to the field length limit. Or, we haven't fully removed field length validation. Could we maybe add a new normal test to the [macro tests](https://github.com/tokio-rs/tracing/blob/master/tracing/tests/macros.rs) that tries to create a span with > 32 fields, just to make sure that it works?

2023-09-05 17:46 UTC, eopb commented
> Hmm, actually, it looks like that test _did_ run on this PR, and it _did_ fail to compile: https://github.com/tokio-rs/tracing/actions/runs/6087610980/job/16516577365?pr=2508#step:6:186
> 
> This makes me concerned that there's some other reason that test doesn't compile, in addition to the field length limit. Or, we haven't fully removed field length validation. Could we maybe add a new normal test to the [macro tests](https://github.com/tokio-rs/tracing/blob/master/tracing/tests/macros.rs) that tries to create a span with > 32 fields, just to make sure that it works?

```
error: cannot find macro `span` in this scope
 --> tracing/src/lib.rs:395:16
  |
6 | let bad_span = span!(
  |                ^^^^
  |
help: consider importing this macro
  |
4 + use tracing::span;
  |

error: aborting due to previous error
```
The test wasn't failing for the right reasons :)

2023-09-05 17:48 UTC, eopb commented
@hawkw Fixed and I've added a test

2023-09-05 17:52 UTC, hawkw approved these changes
fantastic, thank you! let's merge this as soon as CI passes! :)

2023-09-05 17:57 UTC, merged