subscriber: update time crate to 0.3.18
tokio-rs/tracing pull request #2550
Opened 2023-04-07 17:36 UTC by keepsimple1

## Motivation

As I asked earlier in [discussions](https://github.com/tokio-rs/tracing/discussions/2545), I'm trying to use `LocalTime` in `tracing-subscriber::fmt`, i.e. something like this: 
```
tracing_subscriber::fmt()
        .with_timer(tracing_subscriber::fmt::time::LocalTime::rfc_3339())
```

However, with the `time` crate 0.3.2, I need to build with `--cfg unsound_local_offset`, which is not desirable. In fact, `time` crate has removed this requirement since v0.3.18. Hence I propose to update `time` crate version in this branch.

## Solution

Update `time` crate to version `0.3.18`. I tried locally to use `LocalTime` after updating, there is no problem without `--cfg unsound_local_offset`.

2023-04-07 19:16 UTC, hawkw requested changes
Thanks for the PR, I'm happy to increase the minimum `time` version.

There are notes in the docs here https://github.com/tokio-rs/tracing/blob/b28c9351dd4f34ed3c7d5df88bb5c2e694d9c951/tracing-subscriber/src/fmt/time/time_crate.rs#L9-L20 and here https://github.com/tokio-rs/tracing/blob/b28c9351dd4f34ed3c7d5df88bb5c2e694d9c951/tracing-subscriber/src/fmt/time/time_crate.rs#L99-L110 discussing the `unsound_local_offset` cfg. If we're going to upgrade to a version of `time` where this is no longer required, we should also remove these notes from the documentation, so that users don't think they still need to enable that flag.

2023-04-07 20:31 UTC, hawkw approved these changes
looks good to me, thanks!

2023-04-07 21:29 UTC, keepsimple1 commented
Thanks for reviewing and approving! There are some failures in CI. I'm not sure if they are related to this change (my guess is not, except the MSRV failures).  Should I debug these CI errors?

2023-04-07 22:39 UTC, hawkw commented
> Thanks for reviewing and approving! There are some failures in CI. I'm not sure if they are related to this change (my guess is not, except the MSRV failures). Should I debug these CI errors?

It looks like a majority of the failing checks aren't related to this change. I you have the time to dig into them, that would be appreciated, but let's try and land any changes that fix stuff unrelated to this change in separate PRs please?

2023-04-08 18:03 UTC, keepsimple1 commented
> It looks like a majority of the failing checks aren't related to this change. I you have the time to dig into them, that would be appreciated, but let's try and land any changes that fix stuff unrelated to this change in separate PRs please?

Sure. I started with Clippy warnings: https://github.com/tokio-rs/tracing/pull/2552 .

2023-04-10 12:40 UTC, davidbarsky commented
Should this PR be pointing at the 0.1 branch? Has this been fixed on master?

2023-04-10 16:14 UTC, keepsimple1 commented
> Should this PR be pointing at the 0.1 branch? Has this been fixed on master?

It's the [same on master](https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/Cargo.toml#L52). I submitted the change for 0.1.x as that's what I'm using ;-). I don't know what's the process of re-applying / cherrypicking a fix, but I can submit it again for master after this PR lands successfully.

2023-04-10 16:38 UTC, hawkw commented
> > Should this PR be pointing at the 0.1 branch? Has this been fixed on master?
> 
> It's the [same on master](https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/Cargo.toml#L52). I submitted the change for 0.1.x as that's what I'm using ;-). I don't know what's the process of re-applying / cherrypicking a fix, but I can submit it again for master after this PR lands successfully.

In general, we prefer to land new changes on master and then the maintainers will backport them to v0.1.x. If you have the time and energy to cherry-pick your own PR, though, that would be much appreciated!

2023-04-10 17:05 UTC, davidbarsky commented
> It's the [same on master](https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/Cargo.toml#L52). I submitted the change for 0.1.x as that's what I'm using ;-). I don't know what's the process of re-applying / cherrypicking a fix, but I can submit it again for master after this PR lands successfully.

Yeah, what Eliza said. It's a lot easier for us to cherry-pick in a single direction. If you're using this, I'd be happy to prioritize a cherry-pick quickly.

I'd suggest using `git cherry-pick -Xfind-renames $SOME_COMMIT`—it handles renamed files quite nicely.

2023-04-10 23:45 UTC, keepsimple1 commented
I have changed the base to `master`. I need to rebase the source branch and push again.

2023-04-11 01:07 UTC, keepsimple1 commented
I've rebased the diff against `master`. Thanks for your suggestions.

2023-04-12 21:06 UTC, hawkw approved these changes
looks good to me, thanks!

2023-04-12 23:31 UTC, keepsimple1 commented
CI MSRV checked [failed with rust 1.56.0](https://github.com/tokio-rs/tracing/actions/runs/4682380261/jobs/8297356429?pr=2550). I think it's because `time` crate 0.3.18 specified [`rust-version = "1.62.0"`](https://github.com/time-rs/time/blob/3df112071931d098ce440def59f2490043d4582d/time/Cargo.toml#L6).  

I guess we can't update `time` crate to 0.3.18 until CI moves to later Rust versions? Any plans to bump up Rust version for CI?

2023-04-13 20:24 UTC, merged

2023-04-13 21:57 UTC, hawkw commented
> CI MSRV checked [failed with rust 1.56.0](https://github.com/tokio-rs/tracing/actions/runs/4682380261/jobs/8297356429?pr=2550). I think it's because `time` crate 0.3.18 specified [`rust-version = "1.62.0"`](https://github.com/time-rs/time/blob/3df112071931d098ce440def59f2490043d4582d/time/Cargo.toml#L6).
> 
> I guess we can't update `time` crate to 0.3.18 until CI moves to later Rust versions? Any plans to bump up Rust version for CI?

Whoops, I didn't see this comment when this PR was merged. That's unfortunate, I think we may have to revert this change to maintain our current MSRV policy. However, if we go back to specifying a more permissive dependency on `time` that _allows_ but does not _require_ v0.3.18, users on Rust 1.62+ can explicitly specify `time` v0.3.18 in their dependencies to avoid having to use `--cfg unsound_local_offset`. We can document that if you specify `time` v0.3.18+ in your `Cargo.toml` or `Cargo.lock`, you no longer need to use this flag.

2023-04-13 23:00 UTC, keepsimple1 commented
> Whoops, I didn't see this comment when this PR was merged. That's unfortunate, I think we may have to revert this change to maintain our current MSRV policy. However, if we go back to specifying a more permissive dependency on `time` that _allows_ but does not _require_ v0.3.18, users on Rust 1.62+ can explicitly specify `time` v0.3.18 in their dependencies to avoid having to use `--cfg unsound_local_offset`. We can document that if you specify `time` v0.3.18+ in your `Cargo.toml` or `Cargo.lock`, you no longer need to use this flag.

Did you mean we revert and add `~` :  
```
[dependencies]
time = "~0.3.2"
```
and also document like you said? 

(I never used `~`, so not completely sure)