Bump matchers
tokio-rs/tracing pull request #3033
Opened 2024-07-14 20:23 UTC by oscargus

## Motivation

See #2945

## Solution

Instead of removing it, make use of the recently released version.

(Not sure the tests pass as some tests fail on my Windows machine without this modification... So better to run it here.)

2024-07-15 11:45 UTC, BurntSushi commented
> Same error, but it has changed name between 0.1 and 0.2, so not clear if one can include this in the 0.3-series...

From a quick glance, it looks like this error type is on the `FromStr` impl for `MatchPattern` and `MatchPattern` is not part of the public API. So this change should be okay.

2024-07-15 15:04 UTC, BurntSushi commented
(I'm just the `regex-automata` author here looking to see folks move off of `regex-automata 0.1`, I'm not sure about tokio's processes here. Apologies.)

2024-07-16 10:47 UTC, mladedav commented
Generally, the maintainers handle backporting to `v0.1.x`.

2024-07-21 18:39 UTC, hawkw commented
> > Same error, but it has changed name between 0.1 and 0.2, so not clear if one can include this in the 0.3-series...
> 
> From a quick glance, it looks like this error type is on the `FromStr` impl for `MatchPattern` and `MatchPattern` is not part of the public API. So this change should be okay.

Yup, that's correct, this shouldn't be a breaking change AFAICT.

> Btw, I noted that you have a separate branch for the releases. Is this, if merged, (automatically) backported or should I create a similar PR against the v0.1.x-branch?

We merge PRs into the `master` branch and they are backported to `v0.1.x` by the maintainers. I can take care of that. Thank you!

2024-07-21 18:42 UTC, hawkw requested changes
Thanks for working on this!

It looks like the `matchers::BuildError` type doesn't implement `std::error::Error`, which breaks some code that uses `?` on it in a method that returns `Box<dyn Error + Send + Sync>`: https://github.com/tokio-rs/tracing/actions/runs/9930533323/job/27719987902?pr=3033#step:7:218

I think that, in order to fix that, we should add our own private, internal error type for the `FromStr` impl for MatchPattern` that wraps the `matchers::BuildError` and implements `std::error::Error`. This wrapper type doesn't need to be public, it just needs to be able to be converted into a `Box<dyn std::error::Error + Send + Sync>`

2024-08-01 22:12 UTC, sophie-h commented
Why not go with the 90 loc in https://github.com/tokio-rs/tracing/pull/2945 if this needs extra code anyways?

2024-08-02 11:07 UTC, oscargus commented
> I think that, in order to fix that, we should add our own private, internal error type for the `FromStr` impl for MatchPattern`that wraps the`matchers::BuildError`and implements`std::error::Error`. This wrapper type doesn't need to be public, it just needs to be able to be converted into a `Box<dyn std::error::Error + Send + Sync>`

I'll check with more rust-knowledgeable colleagues what this really means and see if I can implement that. :-)

Then, I guess, one can compare with #2945.

(It also seems to make sense, and possibly be easier, to have `matchers::BuildError` to implement `std::error::Error`? Although that requires an additional release of matchers etc. Anyway, I opened https://github.com/hawkw/matchers/issues/7 . So let's see what comes first...)

2024-08-16 09:41 UTC, oscargus commented
@hawkw Would you mind starting the workflow? Interesting to see if this solves the issue and then we/you can discuss if it is an acceptable solution.

2024-08-23 05:04 UTC, scottlamb commented
I'd also like to see the duplicate `regex-automata` version eliminated. As in, a variation of this PR backported to 0.1.x.

> If I read the blame correct, [a dep on `regex-automata/std`] was included in regex 1.9 [when `regex/std` is enabled]. I'll bump that dependency to see what happens and then one can discuss if that is a viable solution.

I think that works now but is fragile. `regex-automata` isn't part of `regex`'s public API afaict, so some future version of `regex` could stop depending on `regex-automata/std`.

> Alternatively, I think (my detailed knowledge of the Rust eco-system is not 100%) one can add a dependency on regex_automata with the std feature if one would like to avoid bumping regex?

I think that's better, or matchers always enabling `regex-automata/std`. I sent off a PR for the latter just now: https://github.com/hawkw/matchers/pull/8

2024-12-13 20:51 UTC, asomers commented
ping.  Is there any chance we can get this merged?  It's still resulting in a lot of binary bloat downstream.

2024-12-16 18:39 UTC, kanpov commented
Another ping, seems like an easy change to make.

2025-01-20 15:09 UTC, jalil-salame commented
Closes #2923, I tried rebasing this PR and I am getting a bunch of tests failures (both with this PR and on `master`, might be a NixOS issue though).

2025-04-01 16:13 UTC, asomers commented
ping @oscargus @hawkw  any chance we could finish this PR soon?  The downstream issues persist.

2025-04-07 12:58 UTC, dmitrmax commented
I was going to open PR for bumping matchers but checked the tracker out and found 4 opened PR's regarding this issue.

Any chances to see this soon? It is almost a year since it was opened.

2025-05-26 16:40 UTC, jplatte commented on tracing-subscriber/Cargo.toml
> +regex-automata = { optional = true, version = "0.4", default-features = false, features = ["std"] }
I don't understand, what are the new dependencies for? They don't seem to be used.

2025-05-26 18:35 UTC, oscargus commented on tracing-subscriber/Cargo.toml
> +regex-automata = { optional = true, version = "0.4", default-features = false, features = ["std"] }
(`regex` is not needed, but I forgot about the details when updating.... Just pushed a new version.)

> It looks like the matchers::BuildError type doesn't implement std::error::Error, which breaks some code that uses ? on it in a method that returns Box<dyn Error + Send + Sync>: https://github.com/tokio-rs/tracing/actions/runs/9930533323/job/27719987902?pr=3033#step:7:218

Basically, regex-automata is a dependency of matchers, but not with the std feature. Hence, code that relies on BuildError implementing std::error::Error can break from this update. Now, we guarantee that the std feature is included (matchers is not no_std anyway) and things work as before.

2025-05-26 20:09 UTC, oscargus commented
Comment added. Good idea indeed!

2025-05-26 20:23 UTC, jplatte approved these changes

2025-05-26 20:38 UTC, jplatte commented
Looks like this needs a `rust-version` bump from 1.63 to 1.65. I'm not a tracing maintainer but I would expect that to be fine. Could you update the PR? Might also need changes in `.github/workflows`.

2025-05-26 20:56 UTC, oscargus commented
Bumped to 1.65. As I changed the CI to run on 1.65, I also bumped all other subcrates to that. Not sure if that is the way to go or not, so split into two commits, where the second in the general bump (and, hence, easy to revert).

(No more changes today, but will be happy to fix any outstanding issues/adjust MSRV tomorrow.)

2025-05-27 06:58 UTC, jplatte commented on tracing-subscriber/src/filter/env/field.rs
> +    fn parse_regex(s: &str) -> Result<Self, matchers::BuildError> {
```suggestion
    #[allow(clippy::result_large_err)]
    fn parse_regex(s: &str) -> Result<Self, matchers::BuildError> {
```

2025-05-27 07:21 UTC, oscargus commented on tracing-subscriber/src/filter/env/field.rs
> +    fn parse_regex(s: &str) -> Result<Self, matchers::BuildError> {
Fixed. (First commit.)

2025-05-27 08:25 UTC, hds approved these changes
Looks good. Thank you for your work on this one!

2025-05-27 08:28 UTC, merged